### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by wanglei8851** [fpusan/SuperPang#1]
Hello,

I have install SuperPang (v=0.8) with conda, and it can normally use **test-SuperPang.py,** but **SuperPang.py** presented an error:

Traceback (most recent call last):
  File "/home/miniconda3/envs/SuperPang/bin/SuperPang.py", line 270, in <module>
    main(parse_args())
  File "/home/miniconda3/envs/SuperPang/bin/SuperPang.py", line 92, in main
    bin_ = f.rsplit('/',1)[1].rsplit('.',1)[0]
IndexError: list index out of range

**Comment by fpusan** [comment]
Hi!
I think I know what's happening there. What is the exact command you are
using to invoke it?
Can you put the input genomes inside a directory and call Superpang with
`-f genomes/*fasta`?

**Comment by fpusan** [comment]
Fixed, should work in the new v0.8.1
