### ISSUE TITLE
There was an error running homogenize.py

### ISSUE THREAD

**Issue by timyerg** [fpusan/SuperPang#10]
Hi!
Thank you for the tool and your active support here.
Following another issue (from SqueezeMeta) I run mOTUlizer on bins from numerous independent SquezeMeta projects and got list of mOTUs with MAGs. Now I run SuperPang on each mOTU as it was suggested. No issues with most of the mOTUs, but one specific mOTU contains about 8000 MAGs, so SuperPang is giving me an error:

```
There was an error running homogenize.py. Please open an issue

Traceback (most recent call last):
  File "/home/miniconda3/envs/SuperPang/lib/python3.8/site-packages/SuperPang/lib/utils.py", line 61, in write_fastq
    outfile.write(f'@{name}\n{seq}\n+\n{qual}\n')
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/miniconda3/envs/SuperPang/bin/homogenize.py", line 332, in <module>
    main(parse_args())
  File "/home/miniconda3/envs/SuperPang/bin/homogenize.py", line 24, in main
    fasta2fastq(args.fasta, current1)
  File "/home/miniconda3/envs/SuperPang/lib/python3.8/site-packages/SuperPang/lib/utils.py", line 65, in fasta2fastq
    write_fastq(read_fasta(fasta), fastq)
  File "/home/miniconda3/envs/SuperPang/lib/python3.8/site-packages/SuperPang/lib/utils.py", line 61, in write_fastq
    outfile.write(f'@{name}\n{seq}\n+\n{qual}\n')
OSError: [Errno 28] No space left on device
```
I run it on HPC with 120 Gb of RAM (HPC report tells me that only around 30 Gb of RAM were used when error occured) and several Tb of storage, also tried to export temp directory to a larger disk with no success.

My question if it is "legal" to separate 8000 MAGs on subsets, create assemblies with SuperPang and then run SuperPang on those assemblies to get one final assembly.
Or, is there a better approach to handle it?

**Comment by fpusan** [comment]
So I think that the problem is happening because there is no more space left in your `/tmp` partition, which is where SuperPang writes the temporary files.
You can edit lines 51 and 52 of the `SuperPang.py` script to make it write the temp files elsewhere (I will add a parameter to control that without editing the script).
However 8000 MAGs sounds definitely like it is too much. You will most likely run out of memory, even if you fix this problem. I had been thinking on ways to make SuperPang more memory efficient, but didn't reach a good solution yet.
- How many SqueezeMeta projects are you combining?
- Are you combining only the bins from DAStools (in the `results/bins` dir) or the bins from all the methods?
- What is your mOTU clustering threshold?
- What is your completeness/contamination cutoff?

**Comment by timyerg** [comment]
> So I think that the problem is happening because there is no more space left in your /tmp partition, which is where SuperPang writes the temporary files.

Exporting temp directory will not solve it?

> How many SqueezeMeta projects are you combining?

There are around 100 projects

> Are you combining only the bins from DAStools (in the results/bins dir) or the bins from all the methods?

Only DAStools

> What is your mOTU clustering threshold?

95%

> What is your completeness/contamination cutoff?

All cutoffs are default:

```
mOTUlize.py --fnas $bins/*.fa -o $out --threads 6

SuperPang.py --fasta $mags --checkm Bins/completness.tsv --output-dir $out --threads 4 --force-overwrite
```

where --fasta $mags leads to the file with mags pathes.

**Comment by fpusan** [comment]
It didn't solve it? What changes have you made to the `SuperPang.py` script? And how did you locate the path of that script?
So I assume $mags contain only the paths for one particular mOTU, right?
What column of the mOTUlizer output did you use to select the MAGs associated to each mOTU?

**Comment by timyerg** [comment]
> It didn't solve it? What changes have you made to the SuperPang.py script? 

No changes to the sript, just exported my temp directory before runing the script:

`export TMPDIR=$TMPDIR`

I will try to modify the script itself as you suggested

> So I assume $mags contain only the paths for one particular mOTU, right?

Yes, only MAGs, associated with that specific mOTU (or mOTU_0000 is not a mOTU and should be ignored?)

> What column of the mOTUlizer output did you use to select the MAGs associated to each mOTU?

MAGs column in the mOTUlizer output

**Comment by fpusan** [comment]
Yeah, that sounds like the right column to use.
I am still surprised that you get 8000 MAGs into a single OTU, for only 100 projects. Are those projects coassemblies, or was each run on a single sample?
I'm asking because we normally work under the assumption that only one MAG per species will be assembled when working with a single sample. This is because we expect assemblers to collapse mostly all intra-species diversity (allele differences, etc). But maybe things are not so simple?

**Comment by timyerg** [comment]
> Yeah, that sounds like the right column to use.

Great! Just finished with rest >1300 mOTUs that do not have so high number of MAGs =)

> I am still surprised that you get 8000 MAGs into a single OTU, for only 100 projects. Are those projects coassemblies, or was each run on a single sample?

Each project is one sample, no coassemblies. Assembly and bins were created by SqueezeMeta.

> I'm asking because we normally work under the assumption that only one MAG per species will be assembled when working with a single sample.

You are right, it is very suspicious. Will double check everything again (though I already checked it).

> But maybe things are not so simple?

It is always not so simple for me...

**Comment by fpusan** [comment]
Let me know if you find something weird after double checking. I am also checking with the author of mOTUlizer (Moritz Buck).
Otherwise I am happy that the rest >1300 worked fine!

**Comment by fpusan** [comment]
Did you include a checkm input file when calling mOTUlizer?
It may be that a lot of low quality MAGs are getting into that particular mOTU.

**Comment by fpusan** [comment]
SuperPang will also be much happier if you give it that file (though it can work without it).
You just need to run checkm on all your MAGs, and redirect stdout to a file.

**Comment by timyerg** [comment]
Modified script also resulted in the same error as before.

I provided completeness info to the SuperPang but I totally forgot to do the same for mOTUlizer! Thank you for pointing it out - I will rerun it with completeness info. Hopefully it will fix the issue. I will let you know when I will get it done!

**Comment by timyerg** [comment]
Hi!
I rerun mOTUlizer with completeness info and set cutoff to 70% completeness and 5% contamination. Now I have only 200 mOTUs instead of 1300 and no more than 50 MAGs in one mOTU. That is making more sense!

Thank you for solving it and sorry for your time since it was my error on the step that actually preceded SuperPang.
I will close the issue.

**Comment by azk001** [comment]
Hi!

I am working with around 450 genomes. I am also getting the same error when I am using the 0.9.4.beta1 version.

But latest version is giving me this error:

ImportError: /usr/lib64/libc.so.6: version `GLIBC_2.25' not found (required by /mmfs1/home/azk0151/miniconda3/envs/SuperPang/lib/python3.8/site-packages/speedict/speedict.cpython-38-x86_64-linux-gnu.so)

Can you please help me how to solve this issue? 


Thank you!
