### ISSUE TITLE
NBP2origins.tsv and graph.NBP2origins.csv contain corrupted SourceContig names

### ISSUE THREAD

**Issue by marade** [fpusan/SuperPang#17]
A few of the SourceContigs names have only the contig name and not the genome name. So if the original file is named "Acinetobacter_baumannii_XJ42.fna" and the contigs are named "1" and "p1", it comes out as just "1" and "p1" under SourceContigs instead of "Acinetobacter_baumannii_XJ42_1" and "Acinetobacter_baumannii_XJ42_p1". (These are fake names. Possibly the bug only occurs for certain types of names.) For most genomes it works properly, but in a large collection some have this bug.

**Comment by fpusan** [comment]
Fixed in v1.3.1!

**Comment by marade** [comment]
Thank you!
