### ISSUE TITLE
multiple file paths for `--fasta`

### ISSUE THREAD

**Issue by nick-youngblut** [fpusan/SuperPang#3]
The potential problem with multiple args for `--fasta` (as in the README: `SuperPang.py --fasta <genome1.fasta> <genome2.fasta> <genomeN.fasta>`) is that if the user has 100's (or 1000's) of genomes and uses the full file paths, the command length can exceed the character limits of the OS. It would be helpful to allow the user to provide a file listing all input fasta files (one per line).

**Comment by fpusan** [comment]
You're absolutely right, fixed. Thanks!
