### ISSUE TITLE
How to improve the mOTUpan core-genome estimation for viruses species?

### ISSUE THREAD

**Issue by yi1873** [fpusan/SuperPang#7]
When I tried to generate the viruses pangenome, I found that the effect mOTUpan estimated the core-genome was not ideal.
How does `SuperPang` improve the core-genome estimation effect of small genome-sized species?

**Comment by fpusan** [comment]
I have not tested it in viruses yet.
Can you elaborate a bit more on what happened? Why do you think it is not "optimal", exactly? What were your expectations and what is the result you got?

**Comment by yi1873** [comment]
Maybe the genome size of viruses is small,  the `core.fasta` file is empty for some viruses.  
Such as `Enterovirus A`

**Comment by fpusan** [comment]
I can reproduce with the HIV genomes that you mentioned in #6.

One problem is that by default SuperPang expects genomes to come from the same ANI>95% cluster. The ANI between the HIV genomes is lower. This can be controlled by using the `-i` parameter, maybe setting up down to 0.8 or 0.7 for HIV. This greatly improves the collapsing of homologous regions, and results in a better looking assembly (when you look at the `graph.fastg` file in Bandage.

Still, mOTUpan is not working correctly even when lowering the `-i` parameter, and I'm not sure why. I have also played around with some other settings in SuperPang that might have helped, but got nothing so far.
I will discuss this with its developer.

For now, you can just manually filter the NBPs according to their coverage.

E.g. I ran SuperPang 0.9.4beta1 (available in conda) on 39 HIV genomes with `SuperPang.py --fasta rawHIV/*fna -i 0.7`.
mOTUpan failed to predict a core genomes, but e.g. the header for one of the NBPs I got was: 
`>NODE_Sc0-0-noinfo_length_8924_cov_38.94_tag_noinfo;`

So then I can see that the coverage of that NBP in my original genomes is 38.94, very close to the 39 original genomes (a couple kmers might be missing from one of the input genomes so it's not exactly 39). So I would definitely say that it is core.

Anyways I'll keep looking at this

**Comment by fpusan** [comment]
I discussed this with the creator of mOTUpan, and tweaking some parameters makes it work for your data.
Just go with
`SuperPang.py -f rawHIV/*fna -i 0.7 --force-overwrite -t 24 -x 70` 
The `-i 0.7` part will collapse regions with an ANI>70%. By default it is set to `0.95`, which makes sense for bacterial species but not so much for viruses I guess.
The `-x 70` tweaks mOTUpan's default completeness, which leads to a better core prediction. You can also try even higher values (e.g. 80 or 90).
